# Generated by Django 5.2 on 2025-05-27 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='max_inactive_users',
            field=models.PositiveIntegerField(default=50, help_text='Límite suave para usuarios inactivos. Ayuda a evitar acumulación excesiva.', verbose_name='Máximo de usuarios inactivos'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='max_users',
            field=models.PositiveIntegerField(default=10, verbose_name='Máximo de usuarios activos'),
        ),
    ]
