# Generated by Django 5.2 on 2025-05-28 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0003_remove_organization_max_inactive_users_and_more'),
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='plans.plan', verbose_name='Plan'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='max_users',
            field=models.PositiveIntegerField(default=10, help_text='DEPRECATED: Usar el plan en su lugar', verbose_name='Máximo de usuarios'),
        ),
    ]
