# Generated by Django on 2025-01-26

from django.db import migrations, models


def assign_default_plans(apps, schema_editor):
    """Asignar plan gratuito a organizaciones que no tengan plan"""
    Organization = apps.get_model('orgs', 'Organization')
    Plan = apps.get_model('plans', 'Plan')
    
    try:
        plan_gratuito = Plan.objects.get(name='gratuito')
        
        # Asignar plan gratuito a organizaciones sin plan
        orgs_without_plan = Organization.objects.filter(plan__isnull=True)
        for org in orgs_without_plan:
            org.plan = plan_gratuito
            org.save()
            
    except Plan.DoesNotExist:
        pass


def reverse_assign_plans(apps, schema_editor):
    """Función reversa - no hacer nada"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0004_organization_plan_alter_organization_max_users'),
        ('plans', '0001_initial'),
    ]

    operations = [
        # Asignar planes por defecto antes de cambiar el campo
        migrations.RunPython(assign_default_plans, reverse_assign_plans),
        
        # Cambiar el valor por defecto de max_users
        migrations.AlterField(
            model_name='organization',
            name='max_users',
            field=models.PositiveIntegerField(default=1, help_text='DEPRECATED: Usar el plan en su lugar', verbose_name='Máximo de usuarios'),
        ),
    ] 