# Generated by Django 5.2 on 2025-06-04 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0005_alter_organization_max_users_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='max_users',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='plan',
        ),
    ]
