# Generated by Django 5.2 on 2025-06-10 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0006_remove_organization_max_users_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='slug',
        ),
    ]
