# Generated by Django 5.2 on 2025-05-27 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la plantilla')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('default_username_pattern', models.CharField(default='{nombre}.{apellido}', help_text='Ej: {nombre}.{apellido} o usuario_{numero}', max_length=100, verbose_name='Patrón de nombre de usuario')),
                ('default_email_pattern', models.CharField(default='{username}@empresa.com', help_text='Ej: {username}@empresa.com', max_length=100, verbose_name='Patrón de email')),
                ('default_password', models.CharField(default='CambiarPassword123!', max_length=100, verbose_name='Contraseña por defecto')),
                ('default_is_active', models.BooleanField(default=True, verbose_name='Activo por defecto')),
                ('default_is_org_admin', models.BooleanField(default=False, verbose_name='Admin de org por defecto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Plantilla activa')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_user_templates', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('default_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orgs.organization', verbose_name='Organización por defecto')),
            ],
            options={
                'verbose_name': 'Plantilla de Usuario',
                'verbose_name_plural': 'Plantillas de Usuario',
                'ordering': ['name'],
            },
        ),
    ]
