# Generated by Django 5.2 on 2025-05-27 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0002_organization_max_inactive_users_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='max_inactive_users',
        ),
        migrations.AlterField(
            model_name='organization',
            name='max_users',
            field=models.PositiveIntegerField(default=10, help_text='Límite total de usuarios (activos e inactivos)', verbose_name='Máximo de usuarios'),
        ),
    ]
