# Generated by Django 5.2 on 2025-08-01 01:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('trial', 'Prueba Gratuita'), ('basic', 'Plan Básico')], max_length=50, unique=True, verbose_name='Nombre del plan')),
                ('display_name', models.CharField(max_length=100, verbose_name='Nombre para mostrar')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio')),
                ('max_users', models.PositiveIntegerField(default=1, verbose_name='Máximo de usuarios')),
                ('trial_days', models.PositiveIntegerField(default=0, help_text="Para planes 'trial', establece la duración de la prueba.", verbose_name='Días de prueba')),
                ('grace_period_days', models.PositiveIntegerField(default=0, help_text='Días de gracia después de la expiración antes de restringir el acceso.', verbose_name='Días de gracia')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de inicio')),
                ('end_date', models.DateTimeField(verbose_name='Fecha de vencimiento')),
                ('grace_end_date', models.DateTimeField(blank=True, null=True, verbose_name='Fin del período de gracia')),
                ('subscription_status', models.CharField(choices=[('trial_active', 'Trial Activo'), ('trial_expired', 'Trial Expirado'), ('basic_active', 'Plan Básico Activo'), ('basic_grace', 'Plan Básico en Gracia'), ('basic_expired', 'Plan Básico Expirado')], default='trial_active', max_length=20, verbose_name='Estado de Suscripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='orgs.organization')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plans.plan', verbose_name='Plan Actual')),
            ],
            options={
                'verbose_name': 'Suscripción',
                'verbose_name_plural': 'Suscripciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('payment_method', models.CharField(choices=[('manual', 'Pago Manual'), ('upgrade', 'Upgrade')], default='manual', max_length=20, verbose_name='Método de Pago')),
                ('payment_type', models.CharField(choices=[('subscription', 'Suscripción'), ('upgrade', 'Upgrade'), ('trial_to_paid', 'Activación Trial')], default='subscription', max_length=20, verbose_name='Tipo de Pago')),
                ('status', models.CharField(choices=[('completed', 'Completado')], default='completed', max_length=20, verbose_name='Estado')),
                ('processed_by', models.CharField(max_length=100, verbose_name='Procesado por')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('days_added', models.PositiveIntegerField(default=0, verbose_name='Días agregados')),
                ('old_end_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha anterior de vencimiento')),
                ('new_end_date', models.DateTimeField(blank=True, null=True, verbose_name='Nueva fecha de vencimiento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='plans.subscription')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UpgradeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto del upgrade')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], default='pending', max_length=20, verbose_name='Estado')),
                ('approved_by', models.CharField(blank=True, max_length=100, verbose_name='Aprobado por')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='plans.plan')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upgrade_requests', to='orgs.organization')),
                ('requested_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='plans.plan')),
            ],
            options={
                'verbose_name': 'Solicitud de Upgrade',
                'verbose_name_plural': 'Solicitudes de Upgrade',
                'ordering': ['-created_at'],
            },
        ),
    ]
