# Generated by Django 5.2 on 2025-06-04 19:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0006_remove_organization_max_users_and_more'),
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['sort_order', 'price'], 'verbose_name': 'Plan', 'verbose_name_plural': 'Planes'},
        ),
        migrations.AddField(
            model_name='plan',
            name='billing_cycle',
            field=models.CharField(choices=[('monthly', 'Mensual'), ('annual', 'Anual'), ('trial', 'Prueba Gratuita')], default='monthly', max_length=20, verbose_name='Ciclo de facturación'),
        ),
        migrations.AddField(
            model_name='plan',
            name='currency',
            field=models.CharField(default='MXN', max_length=3, verbose_name='Moneda'),
        ),
        migrations.AddField(
            model_name='plan',
            name='features',
            field=models.JSONField(blank=True, default=dict, help_text='JSON con características específicas del plan', verbose_name='Características'),
        ),
        migrations.AddField(
            model_name='plan',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Plan destacado'),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_projects',
            field=models.PositiveIntegerField(default=1, verbose_name='Máximo de proyectos'),
        ),
        migrations.AddField(
            model_name='plan',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Orden de visualización'),
        ),
        migrations.AddField(
            model_name='plan',
            name='storage_limit_gb',
            field=models.PositiveIntegerField(default=1, verbose_name='Límite de almacenamiento (GB)'),
        ),
        migrations.AddField(
            model_name='plan',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Stripe Price ID'),
        ),
        migrations.AddField(
            model_name='plan',
            name='stripe_product_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Stripe Product ID'),
        ),
        migrations.AddField(
            model_name='plan',
            name='trial_days',
            field=models.PositiveIntegerField(default=0, help_text='Solo aplica para planes de prueba', verbose_name='Días de prueba'),
        ),
        migrations.AddField(
            model_name='plan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='max_users',
            field=models.PositiveIntegerField(default=1, verbose_name='Máximo de usuarios'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(choices=[('trial', 'Prueba Gratuita'), ('basic', 'Plan Básico'), ('premium', 'Plan Premium')], max_length=50, unique=True, verbose_name='Nombre del plan'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio'),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de inicio')),
                ('end_date', models.DateTimeField(verbose_name='Fecha de vencimiento')),
                ('trial_end_date', models.DateTimeField(blank=True, null=True, verbose_name='Fin de periodo de prueba')),
                ('status', models.CharField(choices=[('active', 'Activa'), ('trial', 'En Prueba'), ('expired', 'Expirada'), ('cancelled', 'Cancelada'), ('suspended', 'Suspendida')], default='trial', max_length=20, verbose_name='Estado')),
                ('payment_status', models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado'), ('failed', 'Falló'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Estado de pago')),
                ('last_payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Último pago')),
                ('next_billing_date', models.DateTimeField(blank=True, null=True, verbose_name='Próxima facturación')),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Stripe Subscription ID')),
                ('stripe_customer_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Stripe Customer ID')),
                ('auto_renew', models.BooleanField(default=True, verbose_name='Renovación automática')),
                ('cancel_at_period_end', models.BooleanField(default=False, verbose_name='Cancelar al final del periodo')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadatos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='orgs.organization', verbose_name='Organización')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plans.plan', verbose_name='Plan')),
            ],
            options={
                'verbose_name': 'Suscripción',
                'verbose_name_plural': 'Suscripciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
