# Generated by Django 5.2 on 2025-08-01 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_alter_subscription_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='billing_cycle_days',
            field=models.PositiveIntegerField(default=30, help_text='Duración estándar del ciclo de pago en días.', verbose_name='Días del ciclo de facturación'),
        ),
    ]
