# Generated by Django 5.2 on 2025-06-04 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0006_remove_organization_max_users_and_more'),
        ('plans', '0002_alter_plan_options_plan_billing_cycle_plan_currency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UpgradeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendiente de Aprobación'), ('approved', 'Aprobada - Pendiente de Pago'), ('payment_pending', 'Pago Reportado - En Verificación'), ('completed', 'Completada'), ('rejected', 'Rechazada'), ('cancelled', 'Cancelada')], default='pending', max_length=20, verbose_name='Estado')),
                ('requested_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Solicitud')),
                ('approved_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Aprobación')),
                ('completed_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Completado')),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto a Pagar')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='Método de Pago Preferido')),
                ('payment_reference', models.CharField(blank=True, max_length=100, verbose_name='Referencia de Pago')),
                ('payment_proof_info', models.CharField(blank=True, help_text='Descripción del comprobante de pago enviado por email o WhatsApp', max_length=200, verbose_name='Información del Comprobante')),
                ('request_notes', models.TextField(blank=True, verbose_name='Notas de la Solicitud')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Notas del Administrador')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Motivo de Rechazo')),
                ('contact_info', models.JSONField(blank=True, default=dict, verbose_name='Información de Contacto')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upgrade_requests_approved', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por')),
                ('current_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_upgrades', to='plans.plan', verbose_name='Plan Actual')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upgrade_requests', to='orgs.organization', verbose_name='Organización')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upgrade_requests_made', to=settings.AUTH_USER_MODEL, verbose_name='Solicitado por')),
                ('requested_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_upgrades', to='plans.plan', verbose_name='Plan Solicitado')),
            ],
            options={
                'verbose_name': 'Solicitud de Upgrade',
                'verbose_name_plural': 'Solicitudes de Upgrade',
                'ordering': ['-requested_date'],
            },
        ),
    ]
