# Generated by Django 5.2 on 2025-08-01 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_plan_billing_cycle_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='processed_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Procesado por'),
        ),
    ]
